[bfi]
urls = [
  "https://whatson.bfi.org.uk/imax/Online/default.asp",
  "https://whatson.bfi.org.uk/imax/Online/default.asp?BOparam::WScontent::loadArticle::permalink=special-screenings-events",
  "https://whatson.bfi.org.uk/imax/Online/default.asp?BOparam::WScontent::loadArticle::permalink=christopher-nolan-film&BOparam::WScontent::loadArticle::context_id=",
]

[watch]
titles = [
  "Interstellar",
  "Tenet",
  "Dunkirk",
  "Oppenheimer",
  "Inception",
]
watch_nolan_only = false
watch_nolan_season = true

[app]
log_level = "INFO"
save_raw_html = true
raw_html_dir = "data/raw"

browser_timeout_ms = 30000
browser_wait_after_load_ms = 5000
browser_headless = true